In [1]:
import pandas as pd
import numpy as np

In [2]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    '국어': [80, 90, 70],
    '수학': [85, 95, 75],
    '영어': [88, 92, 78]
}, index=['A', 'B', 'C'])

df

   국어  수학  영어
A  80  85  88
B  90  95  92
C  70  75  78

In [3]:
# set_index()는 특정 컬럼을 인덱스로 이동
df.set_index('수학')

    국어  영어
수학
85  80  88
95  90  92
75  70  78

In [4]:
# stack()은 모든 컬럼을 인덱스로 이동
df.stack()

A  국어    80
   수학    85
   영어    88
B  국어    90
   수학    95
   영어    92
C  국어    70
   수학    75
   영어    78
dtype: int64

In [ ]:
# 특정 컬럼만 인덱스로 이동
# .stack이 없으면 국어 수학만 출력됨
df[['국어', '수학']].stack()
# '영어' 컬럼이 보이지 않는 이유는
# df[['국어', '수학']] 으로 영어 컬럼을 미리 제외했기 때문
# 컬럼을 인덱스로 바꾸는데 국어랑 수학만 지정했기에 저렇게 출력

A  국어    80
   수학    85
B  국어    90
   수학    95
C  국어    70
   수학    75
dtype: int64

In [ ]:
import pandas as pd

# 멀티인덱스 컬럼을 가진 DataFrame
df = pd.DataFrame(
    [[80, 85, 90, 95],
     [70, 75, 78, 82]],
    index=['A', 'B'], # 인덱스 지정
    columns=pd.MultiIndex.from_tuples([ # 칼럼 이름을 지정 튜플이 4개 있는 리스트
        ('1학기', '국어'), ('1학기', '수학'),
        ('2학기', '국어'), ('2학기', '수학') # 각 튜플의 첫번쨰는 레벨0 두번쨰는 레벨 1 
    ])
)
df
# 1학기 2학기에 해당하는 부분이 레벨0
# 국어 수학은 레벨 1
# 즉 레벨 2의 칼럼임

  1학기     2학기
   국어  수학  국어  수학
A  80  85  90  95
B  70  75  78  82

In [ ]:
df.stack() 
# 디폴트는 제일 마지막 레벨을 인덱스로 가져옴 그래서 1번 레벨을 가져옴
# 그리고 가는 위치도 제일 마지막 위치로 이동함

      1학기  2학기
A 국어   80   90
  수학   85   95
B 국어   70   78
  수학   75   82

In [ ]:
# df.stack은 마지막 레벨 (국어, 수학)이 인덱스의 가장 마지막 레벨로 이동
# 디폴트는 df.stack(-1)

In [ ]:
# 특정 레벨을 선택
df.stack(0) # 0이라 했으니까 1학기 2학기를 이동함

       국어  수학
A 1학기  80  85
  2학기  90  95
B 1학기  70  75
  2학기  78  82

In [9]:
df=pd.DataFrame(
    {"key1":list("aabbab"),
     "key2":["one","two","three"]*2,
     "data1":np.random.randn(6),
     "data2":np.random.randn(6)})
df

  key1   key2     data1     data2
0    a    one -0.674425  0.356099
1    a    two -0.507116  0.139187
2    b  three  0.830895  1.517722
3    b    one  1.027887 -0.727661
4    a    two -1.849445  0.127004
5    b  three -1.703361  0.673357

In [ ]:
df["data1"] #

0   -0.674425
1   -0.507116
2    0.830895
3    1.027887
4   -1.849445
5   -1.703361
Name: data1, dtype: float64

In [11]:
group1=df["data1"].groupby(df["key1"])
# 그룹바이 왼쪽은 대상 = data1 // key1은 기준
# key1 컬럼의 값을 기준으로         ←-------- 기준: 컬럼
# data1 컬럼을                    ←-------- 대상: Series
# 그룹으로 나누어라

In [ ]:
df[["key1", "data1"]]
#기준에 해당하는 컬럼과 대상을 지정

  key1     data1
0    a -0.674425
1    a -0.507116
2    b  0.830895
3    b  1.027887
4    a -1.849445
5    b -1.703361

In [ ]:
# group1=df["data1"].groupby(df["key1"])에서 group은

# "기준이 무엇인 시리즈" ←----- 그룹 1
# "기준이 무엇인 시리즈" ←----- 그룹 2
# ...
# "기준이 무엇인 시리즈" ←----- 그룹 n
# 로 구성

# group1
# ├── 'a'             ←----- 그룹명
# │    0   -0.2816
# │    1   -0.3085
# │    4   -2.6236
# │
# └── 'b'             ←----- 그룹명
#      2    1.6443
#      3   -0.6814
#      5   -0.5932

group1 # 그룹만 실행하면 아무것도 출력되지 않음

In [ ]:
# 1. 그룹 목록 확인
group1.groups

# {'a': [0, 1, 4], 'b': [2, 3, 5]}  a라 해당하는 인덱스는 0,1,4 b라 해당하는 인덱스는 2,3,5
# 키: 그룹명
# 값: 해당 그룹의 인덱스 리스트

{'a': [0, 1, 4], 'b': [2, 3, 5]}

In [ ]:
# 2. 각 그룹 순회하며 내용 출력

# group
# ├── 'a'             ←----- 그룹명 (name)
# │    0   -0.2816
# │    1   -0.3085
# │    4   -2.6236
# │
# └── 'b'             ←----- 그룹명 (name)
#      2    1.6443
#      3   -0.6814
#      5   -0.5932

for name, _ in group1: # 이름만 출력함
    print(name)

print('-'*100)

for _, g in group1: # 그룸의 누가 있는가를 출력 
    print(g)# 시리즈를 두개 출력하는데 a랑 b를 출력

print('-'*100)

for name, g in group1: #이름과 시리즈를 모두 출력함
    print(name, g)

a
b
----------------------------------------------------------------------------------------------------
0   -0.674425
1   -0.507116
4   -1.849445
Name: data1, dtype: float64
2    0.830895
3    1.027887
5   -1.703361
Name: data1, dtype: float64
----------------------------------------------------------------------------------------------------
a 0   -0.674425
1   -0.507116
4   -1.849445
Name: data1, dtype: float64
b 2    0.830895
3    1.027887
5   -1.703361
Name: data1, dtype: float64

In [ ]:
# 3. 특정 그룹
group1.get_group("a") #특정한 그룹만 출력 get_group

0   -0.674425
1   -0.507116
4   -1.849445
Name: data1, dtype: float64

In [ ]:
group1.mean() # 집계함수 집계란? 글자가 있고 말이 있음  mean = 평균 
# key1은 그럼이 이렇게 나누어져있다
# a의 평균 , b의 평균 을 알려줌

key1
a   -1.010329
b    0.051807
Name: data1, dtype: float64

In [ ]:
group2=df["data1"].groupby([df["key1"], df["key2"]]) #key값이 두개
# key1 컬럼, key1 컬럼의 값을 기준으로         ←-------- 기준: 컬럼
# data1 컬럼을                              ←-------- 대상: Series
# 그룹으로 나누어라 → key1, key2가 모두 같아야 같은 그룹

In [ ]:
df[["key1", "key2", "data1"]] # k1,k2는 기준 data1은 대상 
#a1,a2 b1,b3

  key1   key2     data1
0    a    one -0.674425
1    a    two -0.507116
2    b  three  0.830895
3    b    one  1.027887
4    a    two -1.849445
5    b  three -1.703361

In [ ]:
for name, _ in group2:
    print(name) # 그래서 이름이 두개

print('-'*100)

for _, g in group2:
    print(g)

print('-'*100)

for name, g in group2:
    print(name, g)

('a', 'one')
('a', 'two')
('b', 'one')
('b', 'three')
----------------------------------------------------------------------------------------------------
0   -0.674425
Name: data1, dtype: float64
1   -0.507116
4   -1.849445
Name: data1, dtype: float64
3    1.027887
Name: data1, dtype: float64
2    0.830895
5   -1.703361
Name: data1, dtype: float64
----------------------------------------------------------------------------------------------------
('a', 'one') 0   -0.674425
Name: data1, dtype: float64
('a', 'two') 1   -0.507116
4   -1.849445
Name: data1, dtype: float64
('b', 'one') 3    1.027887
Name: data1, dtype: float64
('b', 'three') 2    0.830895
5   -1.703361
Name: data1, dtype: float64

In [ ]:
ave = group2.mean()
ave # mean은 평균을 의미하고 a의1,2 b의 1,3의 평균을 각각 표현함
# 타입이 멀티 인덱스

key1  key2
a     one     -0.674425
      two     -1.178280
b     one      1.027887
      three   -0.436233
Name: data1, dtype: float64

In [ ]:
ave.index

# MultiIndex([('a',   'one'),
#             ('a',   'two'),
#             ('b',   'one'),
#             ('b', 'three')],
#            names=['key1', 'key2']) #key1 레벨0에 붙은 인덱스 이름 key2는 레벨 1에 붙은 인덱스 이름

# 레벨 0: key1 ('a', 'b')  ← 바깥쪽
# 레벨 1: key2 ('one', 'two', 'three') ← 안쪽

MultiIndex([('a',   'one'),
            ('a',   'two'),
            ('b',   'one'),
            ('b', 'three')],
           names=['key1', 'key2'])

In [ ]:
# unstack()은 인덱스를 컬럼으로 이동한다는 점에서 reset_index()와 유사
# 하지만 unstack()은 멀티인덱스 상황에서 특정 인덱스를 컬럼으로 이동

# unstack()의 디폴트는 가장 마지막 레벨을 컬럼으로
# 즉, 디폴트는 unstack(-1) -1은 마자막 레벨을 의미

ave.unstack()
# 결측치가 생기는 이유는 {a, b} x {one, two , three} 모든 조합이 있지 않기 때문
# 결측치는 a에는 three가 없으니 생기고 b에는 two가 없으니 생김

key2       one     three      two
key1
a    -0.674425       NaN -1.17828
b     1.027887 -0.436233      NaN

In [ ]:
ave.unstack(0)
# 평균에서 결측치가 생기는 이유도 위와같음

key1          a         b
key2
one   -0.674425  1.027887
three       NaN -0.436233
two   -1.178280       NaN

In [25]:
df2 = pd.DataFrame({
    "부서": ["영업", "영업", "개발", "개발", "영업", "개발"],
    "연봉": [8000, 6000, 9000, 7000, 5000, 8500],
    "나이": [50, 40, 48, 35, 38, 45]
    
})
df2

   부서    연봉  나이
0  영업  8000  50
1  영업  6000  40
2  개발  9000  48
3  개발  7000  35
4  영업  5000  38
5  개발  8500  45

In [26]:

group3 = df2.groupby("부서")
group3

In [27]:
for name, _ in group3:
    print(name)

print('-'*100)

for _, g in group3:
    print(g)

print('-'*100)

for name, g in group3:
    print(name, g)

개발
영업
----------------------------------------------------------------------------------------------------
   부서    연봉  나이
2  개발  9000  48
3  개발  7000  35
5  개발  8500  45
   부서    연봉  나이
0  영업  8000  50
1  영업  6000  40
4  영업  5000  38
----------------------------------------------------------------------------------------------------
개발    부서    연봉  나이
2  개발  9000  48
3  개발  7000  35
5  개발  8500  45
영업    부서    연봉  나이
0  영업  8000  50
1  영업  6000  40
4  영업  5000  38

In [ ]:
group3.mean()
# 그래서 부서별로 평균을 구함

             연봉         나이
부서
개발  8166.666667  42.666667
영업  6333.333333  42.666667

In [41]:
df3 = pd.DataFrame({
    "팀": ["A", "A", "B", "B", "A", "B"],
    "점수": [85, 90, 78, 92, 88, 76],
    "출석": [20, 18, 22, 19, 21, 20]
})

group4 = df3.groupby("팀")
group4.mean()

# 나중에 밑에 있는 기본 통계 함수 부분 다시 넣어서 공부

          점수         출석
팀
A  87.666667  19.666667
B  82.000000  20.333333

In [ ]:
# 그룹 내의 여러 값을 하나로 줄여주는 함수를 집계 함수라고 함
# [0, 3]  →   sum(): 3
# [0, 3]  →  mean(): 1.5
# [0, 3]  →   min(): 0
# [0, 3]  →   max(): 3

# 기본 통계
# 'sum'     # 합계
# 'mean'    # 평균
# 'median'  # 중앙값
# 'min'     # 최솟값
# 'max'     # 최댓값
# 'std'     # 표준편차
# 'var'     # 분산
# 'count'   # 개수 (NaN 제외)
# 'size'    # 개수 (NaN 포함)

# 기타
# 'first'   # 첫 번째 값
# 'last'    # 마지막 값
# 'nunique' # 고유값 개수

In [42]:
group4.nunique()

   점수  출석
팀
A   3   3
B   3   3

In [43]:
rng = np.random.RandomState(0)
df = pd.DataFrame({
    'key': ['A', 'B', 'C', 'A', 'B', 'C'],
    'data1': range(6),
    'data2': rng.randint(0, 10, 6)
})
df

  key  data1  data2
0   A      0      5
1   B      1      0
2   C      2      3
3   A      3      3
4   B      4      7
5   C      5      9

In [44]:
# aggregate()는 여러 집계 함수를 한번에 적용
df.groupby('key').aggregate(['min', np.median, 'max']) #min max는 문자열 처럼 사용 np.median 은 넘파이에서 지원하는 형식

    data1            data2
      min median max   min median max
key
A       0    1.5   3     3    4.0   5
B       1    2.5   4     0    3.5   7
C       2    3.5   5     3    6.0   9

In [ ]:
df

In [ ]:
# groupby('key')는 컬럼 'key'의 unique 값을 인덱스로
# key칼럼에 있는 값을 기준으로 표준편차를 계산하라
df.groupby('key').std()

       data1     data2
key
A    2.12132  1.414214
B    2.12132  4.949747
C    2.12132  4.242641

In [ ]:
#lambda
#lambda함수 -> 1회용 함수 
#그자리에서 만들어 쓰고 끝 
lambda x:x #앞에 x는 내가 넘겨주는 인자값 =  parameter :뒤에는 함수 내용
#lambda parameter:function
lambda x:x+10 #=> 입력을 받아서 10을 더해 리턴을 한다

x = lambda a,b : a*b
print(x(5*6)) # => 30

# 이름이 없음 아무개 함수?
#

In [ ]:
df.groupby('key').filter(lambda x: x['data2'].std()>4) 

# filter(조건)의 형태로 사용

# lambda x: 에서 x는 그룹에 해당; 그룹의 타입은 데이터프레임
# lambda x: x['data']는 그룹의 'data' 컬럼에 해당

# "data2 컬럼의 표준편차가 4보다 큰 그룹만 남겨라"
# 람다함수 나중에 다시 복습

  key  data1  data2
1   B      1      0
2   C      2      3
4   B      4      7
5   C      5      9

In [ ]:
df.groupby('key').filter(lambda x: len(x) == 2)        # 그룹 행 개수가 2 초과
# 약간 이제 조건을 거는 느낌으로 길이가 2인

  key  data1  data2
0   A      0      5
1   B      1      0
2   C      2      3
3   A      3      3
4   B      4      7
5   C      5      9

In [48]:
df.groupby('key').filter(lambda x: x['data2'].max() > 8)

  key  data1  data2
2   C      2      3
5   C      5      9

In [ ]:
#map(lambda,ㅁ)
# filter(lambda, ㅁ)

In [50]:
# use map with lambda function
fruits = ['apple','banana','cherry'] #문자열이 들어있는 리스트
lengths =list(map(lambda x: len(x), fruits)) # map은 람다를 여러곳에서 하고싶을떄 사용
print(lengths)

[5, 6, 6]

In [ ]:
# Use filter with ;ambda function
numbers = [1,2,3,4,5,6,7,8]
evens = filter(lambda x:x %2 ==0 ,numbers) # 얘는 2로 나눈값이 0인지를 확인하는거ㅗㄴ데 true false로 나오고 그거에 대한 값을반환
print(list(evens))

[2, 4, 6, 8]