In [4]:
# import module
import pandas as pd

# assign data
df = pd.DataFrame({'Name': ['RACHEL', 'MONICA', 'PHOEBE',
                                   'ROSS', 'CHANDLER', 'JOEY'],
                          'Age': [30, 35, 37, 33, 34, 30],
                          'Salary': [100000, 93000, 88000, 120000, 94000, 95000],
                          'JOB': ['DESIGNER', 'CHEF', 'MASUS', 'PALENTOLOGY',
                                  'IT', 'ARTIST']})

df

       Name  Age  Salary          JOB
0    RACHEL   30  100000     DESIGNER
1    MONICA   35   93000         CHEF
2    PHOEBE   37   88000        MASUS
3      ROSS   33  120000  PALENTOLOGY
4  CHANDLER   34   94000           IT
5      JOEY   30   95000       ARTIST

In [5]:
df.loc[(df['Salary']>=100000) & (df['Age']< 40) & (df['JOB'].str.startswith('D')), ['Name','JOB']]

     Name       JOB
0  RACHEL  DESIGNER

In [6]:
import pandas as pd
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 35, 40],
        'Score': [85, 90, 95, 80]}
df = pd.DataFrame(data)
df

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95
3    David   40     80

sort_values가 따로 정해지지 않았으니 age 기준으로 오름차순으로 정렬(기본값)

In [7]:
sorted_df = df.sort_values(by='Age')
print(sorted_df)

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95
3    David   40     80

ascending이 false 이므로 내림차순

In [8]:
sorted_df = df.sort_values(by='Age',ascending=False)
print(sorted_df)

      Name  Age  Score
3    David   40     80
2  Charlie   35     95
1      Bob   30     90
0    Alice   25     85

ignore_index(True)라 하면 인덱스를 정렬에 포함하지 않음이라는거 위랑 다른점을 비교하면 보임 
주의할점은 원래 인덱스가 뭔지 모르기떄문에 조심해야하ㅁ

In [9]:
sorted_df = df.sort_values(by='Age',ascending=False, ignore_index=True)
print(sorted_df)

      Name  Age  Score
0    David   40     80
1  Charlie   35     95
2      Bob   30     90
3    Alice   25     85

아래의것을 하면 정렬된 상태로 원본이바뀜

In [ ]:
# inplace=True

In [10]:
import pandas as pd
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 35, 40],
        'Score': [85, 90, 95, 80]}
df = pd.DataFrame(data)
df

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95
3    David   40     80

age가 같은경우 다른 조건으로 score로 비교해서 순서를 정함

In [11]:
# 'Age' 값이 같은 경우, 'Score'로 sorting
sorted_df = df.sort_values(by=['Age', 'Score'])
print(sorted_df)

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95
3    David   40     80

원본 데이터에는 none이지만 표시될때는 nan으로 표시됨 missing data는 시각화랑 연결됨 
데이타프레임을 만들때 데이터는 csv파일에 있음

In [13]:
import pandas as pd
data_with_nan = {"Name": ["Alice", "Bob", "Charlie", "David"],"Age": [28, 22, None, 22]}
df_nan = pd.DataFrame(data_with_nan)
df_nan

      Name   Age
0    Alice  28.0
1      Bob  22.0
2  Charlie   NaN
3    David  22.0

sorting을 할떄 결측치가 있으면 그 값에대한 기본값은 마지막으로 감

In [14]:
# default: 결측치는 마지막으로

# sorted_df = df_nan.sort_values(by="Age", na_position="first")
sorted_df = df_nan.sort_values(by="Age")
print(sorted_df)

      Name   Age
1      Bob  22.0
3    David  22.0
0    Alice  28.0
2  Charlie   NaN

In [ ]:
# 인덱스 정렬

In [15]:
import pandas as pd
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 35, 40],
        'Score': [85, 90, 95, 80]}
df = pd.DataFrame(data)
df

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95
3    David   40     80

index를 기준으로 정렬 기본값은 ascending

In [16]:
# default는 ascending 순서
df_sorted_by_index = df.sort_index()
print(df_sorted_by_index)

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95
3    David   40     80

In [17]:
df_sorted_by_index_desc = df.sort_index(ascending=False)
print(df_sorted_by_index_desc)

      Name  Age  Score
3    David   40     80
2  Charlie   35     95
1      Bob   30     90
0    Alice   25     85

In [ ]:
# CSV 파일을 dataframe으로 읽어오기

In [18]:
df = pd.read_csv("people_data.csv")
df

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
1,Phillip,Summers,Female,bethany14@example.com,1910-03-24,Phytotherapist
2,Kristine,Travis,Male,bthompson@example.com,1992-07-02,Homeopath
3,Yesenia,Martinez,Male,kaitlinkaiser@example.com,2017-08-03,Market researcher
4,Lori,Todd,Male,buchananmanuel@example.net,1938-12-01,Veterinary surgeon

usecols = 특정 칼럼들만 가져와라(형식은 list)

In [19]:
# 특정 컬럼만 불러오기

df = pd.read_csv("people_data.csv", usecols=["First Name", "Email"])
df

  First Name                       Email
0     Shelby        elijah57@example.net
1    Phillip       bethany14@example.com
2   Kristine       bthompson@example.com
3    Yesenia   kaitlinkaiser@example.com
4       Lori  buchananmanuel@example.net

저건 인덱스를 firstname이라고 정해서 출력하는것

In [20]:
# 특정 컬럼을 인덱스로 지정

df = pd.read_csv("people_data.csv", index_col="First Name")
print(df)

           Last Name     Sex                       Email Date of birth  \
First Name
Shelby       Terrell    Male        elijah57@example.net    1945-10-26
Phillip      Summers  Female       bethany14@example.com    1910-03-24
Kristine      Travis    Male       bthompson@example.com    1992-07-02
Yesenia     Martinez    Male   kaitlinkaiser@example.com    2017-08-03
Lori            Todd    Male  buchananmanuel@example.net    1938-12-01

                     Job Title
First Name
Shelby         Games developer
Phillip         Phytotherapist
Kristine             Homeopath
Yesenia      Market researcher
Lori        Veterinary surgeon

N/A나 unknown값이 있다면 저건 NAN 로 바꿔라 라고 명령, scv파일에서 어떤게 결측치인지는 아무도 모르기 떄문어 저렇게 여러 조건을 걸음

In [21]:
# 이런 값이 있으면 NaN으로 바꾸어라 → 결측치 처리

df = pd.read_csv("people_data.csv", na_values=["N/A", "Unknown"])
df

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
1,Phillip,Summers,Female,bethany14@example.com,1910-03-24,Phytotherapist
2,Kristine,Travis,Male,bthompson@example.com,1992-07-02,Homeopath
3,Yesenia,Martinez,Male,kaitlinkaiser@example.com,2017-08-03,Market researcher
4,Lori,Todd,Male,buchananmanuel@example.net,1938-12-01,Veterinary surgeon

nrows = 3 세줄만 불러와라

In [22]:
# 몇 라인만 불러오기

df = pd.read_csv('people_data.csv', nrows=3)
df

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
1,Phillip,Summers,Female,bethany14@example.com,1910-03-24,Phytotherapist
2,Kristine,Travis,Male,bthompson@example.com,1992-07-02,Homeopath

첫 몇라인을 건너뛰는 이유는 csv파일이 추가적인 설명이 있으면 그걸 생략해야 프로그램이 인식할수있기때문에

In [23]:
# 첫 몇 라인은 건너뛰기

df = pd.read_csv("people_data.csv", skiprows = [4,5])
print("Dataset After skipping rows: ")
df

Dataset After skipping rows:

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
1,Phillip,Summers,Female,bethany14@example.com,1910-03-24,Phytotherapist
2,Kristine,Travis,Male,bthompson@example.com,1992-07-02,Homeopath