In [ ]:

import pandas as pd 
import numpy as np

In [41]:
index = [('California', 2000), ('California', 2010),
         ('New York', 2000), ('New York', 2010),
         ('Texas', 2000), ('Texas', 2010)]

index

[('California', 2000),
 ('California', 2010),
 ('New York', 2000),
 ('New York', 2010),
 ('Texas', 2000),
 ('Texas', 2010)]

In [42]:
for x in index:
    print(x[0],x[1])

California 2000
California 2010
New York 2000
New York 2010
Texas 2000
Texas 2010

In [43]:
populations = [33871648, 37253956, 18976457, 19378102, 20851820, 25145561]
populations

[33871648, 37253956, 18976457, 19378102, 20851820, 25145561]

In [50]:
pop = pd.Series(populations, index=index)
# pop = pd.Series(populations)
pop

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64

In [51]:
# 비효율적인 방법

pop[[i for i in pop.index if i[1]==2000]]

(California, 2000)    33871648
(New York, 2000)      18976457
(Texas, 2000)         20851820
dtype: int64

In [54]:
pop.index # 얘는 튜플임

Index([('California', 2000), ('California', 2010),   ('New York', 2000),
         ('New York', 2010),      ('Texas', 2000),      ('Texas', 2010)],
      dtype='object')

In [55]:
# list comprehension
#이건 파이썬 내용
# 1. 기존 리스트의 모든 요소에 특정 연산을 적용하여 새 리스트를 만드는 경우
squares = [x**2 for x in range(10)] #[■ for ■ in ◆]
print(squares)

words = ['python', 'is', 'awesome']
upper_words = [w.upper() for w in words]
print(upper_words)

# 2. 조건에 맞는 요소만 골라내고 나머지는 버림
evens = [x for x in range(1, 21) if x % 2 == 0] #[■ for ■ in ◆ if ●]
print(evens)

fruits = ['apple', 'banana', 'cherry', 'kiwi', 'mango']
a_fruits = [f for f in fruits if 'a' in f]
print(a_fruits)

# 3. 조건에 의해서 새로운 리스트 만들기
numbers = [1, 2, 3, 4, 5]
labels = ['Even' if x % 2 == 0 else 'Odd' for x in numbers] #[■ if ● for ■ in ◆]
print(labels)

# 4. for안에 또 다른 for
matrix = [[1, 2], [3, 4], [5, 6]]
flat = [num for row in matrix for num in row]

print(flat)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
['PYTHON', 'IS', 'AWESOME']
[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
['apple', 'banana', 'mango']
['Odd', 'Even', 'Odd', 'Even', 'Odd']
[1, 2, 3, 4, 5, 6]

In [56]:
matrix = [[1, 2], [3, 4], [5, 6]]

for row in matrix: #[1, 2], [3, 4], [5, 6]
    for num in row: #1,2,3,4,5,6
        print(num)

# 두 for를 한 줄에 쓰면
# for row in matrix for num in row

# 마지막 num을 앞쪽에
# num for row in matrix for num in row

1
2
3
4
5
6

In [57]:
# 5. dictionary comprehension

square_dict = {x: x**2 for x in range(5)}
print(square_dict)

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16}

In [ ]:
# pandas MultiIndex

In [58]:
print(index)

[('California', 2000), ('California', 2010), ('New York', 2000), ('New York', 2010), ('Texas', 2000), ('Texas', 2010)]

In [59]:
print(type(index))

<class 'list'>

In [60]:
index_multi = pd.MultiIndex.from_tuples(index) #얘를 해야 멀티인덱스 타입임
index_multi

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           )

In [61]:
# 1. pd.MultiIndex.from_product

# 별도의 리스트
states = ['California', 'New York', 'Texas']
years = [2000, 2010]

index_multi = pd.MultiIndex.from_product([states, years], names=['state', 'year']) #
print(index_multi)

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           names=['state', 'year'])

In [ ]:
# 리스트의 리스트

arrays = [
    ['California', 'California', 'New York', 'New York', 'Texas', 'Texas'],
    [2000, 2010, 2000, 2010, 2000, 2010]
]
df_info
index_multi = pd.MultiIndex.from_arrays(arrays, names=['state', 'year'])
print(index_multi)

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           names=['state', 'year'])

ctrl + shift + "-" ==> 스플릿 셀 (셀을 나눔)

In [63]:
# 데이터프레임의 컬럼을 사용

df_info = pd.DataFrame({
    'state': ['California', 'California', 'New York', 'New York', 'Texas', 'Texas'],
    'year': [2000, 2010, 2000, 2010, 2000, 2010]
})

df_info

        state  year
0  California  2000
1  California  2010
2    New York  2000
3    New York  2010
4       Texas  2000
5       Texas  2010

In [ ]:
index_multi = pd.MultiIndex.from_frame(df_info)
print(index_multi)

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           names=['state', 'year'])

In [67]:
# set_index 사용

data = {
    'state': ['California', 'California', 'New York', 'New York', 'Texas', 'Texas'],
    'year': [2000, 2010, 2000, 2010, 2000, 2010],
    'pop': [33.8, 37.2, 18.9, 19.3, 20.8, 25.1]
}
df = pd.DataFrame(data)

df_multi = df.set_index(['state', 'year'])

print(df_multi)

                  pop
state      year
California 2000  33.8
           2010  37.2
New York   2000  18.9
           2010  19.3
Texas      2000  20.8
           2010  25.1

In [68]:

df_multi = df.set_index(['state', 'year'])

print(df_multi)

                  pop
state      year
California 2000  33.8
           2010  37.2
New York   2000  18.9
           2010  19.3
Texas      2000  20.8
           2010  25.1

In [69]:
# 현재 pop
pop

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64

In [70]:
pop_multi = pop.reindex(index_multi) # 두대는 서로 다름 
pop_multi

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [ ]:
type(pop_multi) # 하지만 여전히 타입은 시리즈임
# pop_multi의 타입은 Series

In [87]:
# 비효율적인 방법
# pop[[i for i in pop.index if i[1]==2000]]

pop_multi[:, 2000]
# pop_multi의 타입은 Series이기 때문에 컬럼이 하나밖에 없음
# pandas는 pop_multi[:, 2000]을 보고 멀티인덱스라고 판단

# pop_multi가 데이터프레임인 경우 pop_multi[:, 2000]는 에러 발생
# df[행, 열]은 없음, df.loc[], df.iloc[]를 사용해야 함

state
California    33871648
New York      18976457
Texas         20851820
dtype: int64

In [71]:
# 정리

import pandas as pd

data = {
    'state': ['California', 'New York', 'Texas', 'Florida'],
    'year': [2000, 2010, 2000, 2010],
    'pop': [33.8, 37.2, 20.8, 18.8]
}
df = pd.DataFrame(data)
df

        state  year   pop
0  California  2000  33.8
1    New York  2010  37.2
2       Texas  2000  20.8
3     Florida  2010  18.8

In [73]:
# 1. df[]는 기본적으로 컬럼 선택 → 컬럼 타입은 대체로 문자열
# 데이터 프레임이라 하고 []을 쓰면 컬럼 선택임 
col_state = df['state'] # 여기까지는 컬럼 하나 선택
print(col_state)

# 리스트를 넣어서 여러 컬럼 선택
cols = df[['state', 'pop']] # 얘는 여러개의 칼럼 선택  []가 메인임
print(cols)

0    California
1      New York
2         Texas
3       Florida
Name: state, dtype: str
        state   pop
0  California  33.8
1    New York  37.2
2       Texas  20.8
3     Florida  18.8

In [82]:
# 2. df[]에 :를 사용하면 행 선택

rows = df[0:2] # 대괄호에 콜론을쓰면 행을 선택 0~1까지
print(rows)

# df[]에 쉼표가 없다
# 1. 슬라이스 → 행 선택
# 2.   컬럼명 → 열 선택, [컬럼1, 컬럼 2, ...]은 쉼표가 아니라 단일 리스트를 넘긴 것

        state  year   pop
0  California  2000  33.8
1    New York  2010  37.2

In [83]:
# 3. 불리언 마스크를 사용하면 행 선택

mask = df['pop'] > 30
print(df[mask])

        state  year   pop
0  California  2000  33.8
1    New York  2010  37.2

In [84]:
# 컬럼 이름을 알려주지 않음

df = pd.DataFrame([[10, 20], [30, 40]])
# pandas가 디폴트 컬럼 이름 0, 1, 2, ...을 사용
# 이 경우 컬럼명은 숫자 타입에 해당
print(df)
print('-'*100)
print(df[0]) 

#[]에 뭔가를 쓰면 컬럼 : 을쓰면 행 df[0] => 은 컬럼을 선택
#숫자를 썼는데 컬럼인 이유? => 컬럼이 0이어서?
#loc, iloc = > 괄호를 쓰는데 loc는 인덱스를 그대로 iloc는 몇번쨰인지 정함 :를 쓰면 행, 열로 나누어짐
# print(df['0']) # KeyError: '0'

print('-'*100)
print(df[0:2])

    0   1
0  10  20
1  30  40
----------------------------------------------------------------------------------------------------
0    10
1    30
Name: 0, dtype: int64
----------------------------------------------------------------------------------------------------
    0   1
0  10  20
1  30  40

In [ ]:
# pd.Series를 데이터프레임에 끼워넣기

pop_multi # 데이터 프레임은 시리즈가 여러개 붙어있는것

In [88]:
pop_df = pd.DataFrame({
    'total': pop_multi,
    'under18': [9267089, 9284094, 4687374, 4318033, 5906301, 6879014],
}) # 컬럼 단위로 이야기함 가르키는 데이터가 멀티 인덱스 이면 쟤도 같이 멀티인덱스 이다.

pop_df

                    total  under18
state      year
California 2000  33871648  9267089
           2010  37253956  9284094
New York   2000  18976457  4687374
           2010  19378102  4318033
Texas      2000  20851820  5906301
           2010  25145561  6879014

In [93]:
# 인덱스 이름 - 다 만들고 나중에 이름 붙이기

rng = np.random.RandomState(42)
rng.rand(6,3)

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452],
       [0.05808361, 0.86617615, 0.60111501],
       [0.70807258, 0.02058449, 0.96990985],
       [0.83244264, 0.21233911, 0.18182497],
       [0.18340451, 0.30424224, 0.52475643]])

In [96]:
# rng.rand(6, 3)는 난수 생성기(rng)를 사용해서 6행 3열의 2차원 배열을 생성
df = pd.DataFrame(rng.rand(6, 3),  #6행 3열
                  index=[['A', 'A', 'B', 'B', 'C', 'C'], [1,2,1,2,1,2]],
                  columns= ['col1', 'col2', 'col3']
                  )

df

         col1      col2      col3
A 1  0.388677  0.271349  0.828738
  2  0.356753  0.280935  0.542696
B 1  0.140924  0.802197  0.074551
  2  0.986887  0.772245  0.198716
C 1  0.005522  0.815461  0.706857
  2  0.729007  0.771270  0.074045

In [97]:
df.index.names = ['index1', 'index2'] #인덱스 이름을 붙임
df

                   col1      col2      col3
index1 index2
A      1       0.388677  0.271349  0.828738
       2       0.356753  0.280935  0.542696
B      1       0.140924  0.802197  0.074551
       2       0.986887  0.772245  0.198716
C      1       0.005522  0.815461  0.706857
       2       0.729007  0.771270  0.074045

In [98]:
# 인덱스 이름 - 만들면서 알려주기

index_arr = [['A', 'A', 'B', 'B', 'C', 'C'], [1,2,1,2,1,2]]
index = pd.MultiIndex.from_arrays(index_arr, names= ('index1', 'index2'))# name은 name인데 인덱스의 name임 저걸 바꾸면 인덱스 이름이 바뀜
#                                            ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑

df = pd.DataFrame(rng.rand(6,3), 
                  index=index,
                  columns= ['col1', 'col2', 'col3']
                  )

df

                   col1      col2      col3
index1 index2
A      1       0.358466  0.115869  0.863103
       2       0.623298  0.330898  0.063558
B      1       0.310982  0.325183  0.729606
       2       0.637557  0.887213  0.472215
C      1       0.119594  0.713245  0.760785
       2       0.561277  0.770967  0.493796

In [99]:
# 행만 있냐? 컬럼도 있다
row_index = pd.MultiIndex.from_product([[2013, 2014], ['1st', '2nd']], names = ['Year', 'Visit'])
col_index = pd.MultiIndex.from_product([['Bob', 'Guido', 'Sue'], ['HR', 'Temp']], names= ['Patient', 'Data type'])
print(row_index)
print(col_index)

#

MultiIndex([(2013, '1st'),
            (2013, '2nd'),
            (2014, '1st'),
            (2014, '2nd')],
           names=['Year', 'Visit'])
MultiIndex([(  'Bob',   'HR'),
            (  'Bob', 'Temp'),
            ('Guido',   'HR'),
            ('Guido', 'Temp'),
            (  'Sue',   'HR'),
            (  'Sue', 'Temp')],
           names=['Patient', 'Data type'])

↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑\n
위에 보면 names로 인덱스랑 칼럼의 이름을 정의함

In [100]:
data_hr = np.random.randint(50, 80, 12) # 50부터 79까지의 정수중에서 무작위로 12개 선택
data_temp = 37 + np.random.randn(12) # 평균이 0이고 표준편차가 1인 표준정규분포 random number 12개

data_x = [i for i in zip(data_hr, data_temp)]
data_x

[(np.int32(66), np.float64(37.37530395360194)),
 (np.int32(58), np.float64(38.15782874523587)),
 (np.int32(63), np.float64(36.039668966677176)),
 (np.int32(69), np.float64(36.944283265672745)),
 (np.int32(65), np.float64(37.4942379103011)),
 (np.int32(71), np.float64(37.41495782454604)),
 (np.int32(58), np.float64(37.58015789092388)),
 (np.int32(70), np.float64(36.42301184930876)),
 (np.int32(54), np.float64(36.000602773350266)),
 (np.int32(53), np.float64(38.93846844600586)),
 (np.int32(65), np.float64(37.02962405388547)),
 (np.int32(70), np.float64(35.90601128181012))]

In [101]:
arr = np.array(data_x)
arr

array([[66.        , 37.37530395],
       [58.        , 38.15782875],
       [63.        , 36.03966897],
       [69.        , 36.94428327],
       [65.        , 37.49423791],
       [71.        , 37.41495782],
       [58.        , 37.58015789],
       [70.        , 36.42301185],
       [54.        , 36.00060277],
       [53.        , 38.93846845],
       [65.        , 37.02962405],
       [70.        , 35.90601128]])

In [103]:
arr = np.array(data_x)
print(arr.shape)
print(arr)

(12, 2)
[[66.         37.37530395]
 [58.         38.15782875]
 [63.         36.03966897]
 [69.         36.94428327]
 [65.         37.49423791]
 [71.         37.41495782]
 [58.         37.58015789]
 [70.         36.42301185]
 [54.         36.00060277]
 [53.         38.93846845]
 [65.         37.02962405]
 [70.         35.90601128]]

In [102]:
# Reshape to 4 rows and 6 cols # 
#6개로 맞춤
arr_multi = arr.reshape(4,6)
arr_multi

array([[66.        , 37.37530395, 58.        , 38.15782875, 63.        ,
        36.03966897],
       [69.        , 36.94428327, 65.        , 37.49423791, 71.        ,
        37.41495782],
       [58.        , 37.58015789, 70.        , 36.42301185, 54.        ,
        36.00060277],
       [53.        , 38.93846845, 65.        , 37.02962405, 70.        ,
        35.90601128]])

In [104]:
# 이 모든걸 다 합쳐서 데이터 프레임을 만듬
#인덱스 이름 : year, visit 칼럼 이름 : patient, data type
health_data = pd.DataFrame(arr_multi, columns=col_index, index=row_index)
health_data

Patient      Bob            Guido              Sue
Data type     HR       Temp    HR       Temp    HR       Temp
Year Visit
2013 1st    66.0  37.375304  58.0  38.157829  63.0  36.039669
     2nd    69.0  36.944283  65.0  37.494238  71.0  37.414958
2014 1st    58.0  37.580158  70.0  36.423012  54.0  36.000603
     2nd    53.0  38.938468  65.0  37.029624  70.0  35.906011

In [105]:
health_data['Bob'] #이러면 밥에 대한 정보만 출력됨

Data type     HR       Temp
Year Visit
2013 1st    66.0  37.375304
     2nd    69.0  36.944283
2014 1st    58.0  37.580158
     2nd    53.0  38.938468

In [108]:
#health_data['Bob']['HR']# 얘가 멀티 인덱스?
health_data['Bob','HR']

Year  Visit
2013  1st      66.0
      2nd      69.0
2014  1st      58.0
      2nd      53.0
Name: (Bob, HR), dtype: float64

In [ ]:
health_data.loc[2014, ('Bob','HR')] 
# health_data.loc[2014, ['Bob','HR']]

# 튜플은 계층을 표현: ('Bob','HR') → 첫 번째 인덱스는 'Bob', 두 번째 인덱스는 'HR'
# 리스트는 단순 나열임 → 첫 번째 인덱스에 'Bob'은 있지만 'HR'는 없음

Visit
1st    58.0
2nd    53.0
Name: (Bob, HR), dtype: float64

In [110]:
health_data.loc[2014, ['Bob','Sue']]

Patient     Bob              Sue
Data type    HR       Temp    HR       Temp
Visit
1st        58.0  37.580158  54.0  36.000603
2nd        53.0  38.938468  70.0  35.906011