In [1]:
import pandas as pd
import numpy as np

In [2]:
print(type(np.nan))

<class 'float'>

In [3]:
s=pd.Series(["Sam",np.nan,"Tim","Kim"])
s

0    Sam
1    NaN
2    Tim
3    Kim
dtype: str

In [4]:
s.isnull()

0    False
1     True
2    False
3    False
dtype: bool

In [5]:
s.notnull()

0     True
1    False
2     True
3     True
dtype: bool

In [6]:
s[3]=None
s.isnull()

0    False
1     True
2    False
3     True
dtype: bool

dropna만 하면 원본을 바꾸지 않움

In [ ]:
s.dropna()

0    Sam
2    Tim
dtype: str

In [8]:
s

0    Sam
1    NaN
2    Tim
3    NaN
dtype: str

그래서 이렇게 inplace를 넣어줘야함

In [9]:
s.dropna(inplace=True)

In [10]:
s

0    Sam
2    Tim
dtype: str

In [11]:
print(pd.NA)
print(pd.NaT)

<NA>
NaT

In [12]:
# 1
df1 = pd.DataFrame([[1, 2, 3], [4, np.nan, 5], [np.nan, np.nan, np.nan]])

In [13]:
df1

     0    1    2
0  1.0  2.0  3.0
1  4.0  NaN  5.0
2  NaN  NaN  NaN

시리즈 형태로 타입을 알려줌

In [14]:
df1.dtypes

0    float64
1    float64
2    float64
dtype: object

In [15]:
# np.nan은 숫자이기 때문에 float 타입의 컬럼에서 그대로 있음
df1

     0    1    2
0  1.0  2.0  3.0
1  4.0  NaN  5.0
2  NaN  NaN  NaN

In [16]:
# 2
df2 = pd.DataFrame([[1.0, 2.0], [None, 4.0]])

In [17]:
df2.dtypes

0    float64
1    float64
dtype: object

In [18]:
# None은 숫자가 아니기 때문에 float 타입의 컬럼에서 np.nan으로 변환
df2

     0    1
0  1.0  2.0
1  NaN  4.0

타입을 따로 명시하지 않으면 실수타입임

In [19]:
# 3

# 차이는 dtype="Int64"으로 타입을 정했는지의 여부
df3 = pd.DataFrame({"a": [1, None, 3]})
df4 = pd.DataFrame({"a": pd.Series([1, None, 3], dtype="Int64")})

In [20]:
df3

     a
0  1.0
1  NaN
2  3.0

In [21]:
df4

      a
0     1
1  <NA>
2     3

In [22]:
# 4
# NA를 사용한 이유

df5 = pd.DataFrame({"a": [1, None, 3]}) 
# 값 [1, None, 3]은 None을 np.nan으로 바꾸기만 하면 float64이 되네?
# None → np.nan이 되면서 원래는 정수였던 1, 3까지도 실수 타입으로 바뀌어 버림

print(df5.dtypes)

a    float64
dtype: object

In [23]:
df6 = pd.DataFrame({"a": pd.array([1, None, 3], dtype="Int64")})
# 값 1, 3은 정수라고 명시적으로 알림
# 이 경우 None은 np.nan이 아닌 pd.NA로 변환

In [24]:
df6

      a
0     1
1  <NA>
2     3

In [25]:
# 정리하면
# 결측치는 세 종류
# 1. 실수(float) → np.nan
# 2. 정수(Int64) → pd.NA
# 3. 날짜/시간 → pd.NaT

# 문자열의 경우도 pd.NA

df = pd.DataFrame({"a": pd.array(["hello", None, "world"], dtype="string")})
df

       a
0  hello
1   <NA>
2  world

In [26]:

df=pd.DataFrame([[1,2,3],[4, np.nan, 5],
                 [np.nan, np.nan, np.nan]])
df

     0    1    2
0  1.0  2.0  3.0
1  4.0  NaN  5.0
2  NaN  NaN  NaN

In [27]:
df.dtypes

0    float64
1    float64
2    float64
dtype: object

In [28]:
df.dropna() # ---------- 대상은 np.nan, pd.NA, pd.NaT

     0    1    2
0  1.0  2.0  3.0

In [29]:
df.dropna(how="all")
# how="any" (디폴트) → 행에 하나라도 결측치가 있으면 제거
# how="all" → 행의 모든 값이 결측치일 때만 제거

     0    1    2
0  1.0  2.0  3.0
1  4.0  NaN  5.0

In [30]:
df.fillna(0,inplace=True)
df

     0    1    2
0  1.0  2.0  3.0
1  4.0  0.0  5.0
2  0.0  0.0  0.0

In [31]:
df=pd.DataFrame([[1, 2, 3],[4, pd.NA, 5],
                 [pd.NA, pd.NA, pd.NA]])
df

      0     1     2
0     1     2     3
1     4  <NA>     5
2  <NA>  <NA>  <NA>

In [32]:
df.fillna(0)

   0  1  2
0  1  2  3
1  4  0  5
2  0  0  0

In [33]:
df = pd.DataFrame({
    "실수": [1.0, np.nan, 3.0],
    "정수": pd.array([1, None, 3], dtype="Int64"),
    "날짜": pd.to_datetime(["2024-01-01", None, "2024-01-03"]),
    "문자": pd.array(["hello", None, "world"], dtype="string"),
})

In [34]:
df

    실수    정수         날짜     문자
0  1.0     1 2024-01-01  hello
1  NaN  <NA>        NaT   <NA>
2  3.0     3 2024-01-03  world

In [37]:
df.dropna()

    실수  정수         날짜     문자
0  1.0   1 2024-01-01  hello
2  3.0   3 2024-01-03  world

In [38]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "a": [1.0, np.nan, np.nan, 4.0],
    "b": [2.0, np.nan, 3.0,   np.nan],
    "c": [3.0, np.nan, 4.0,   5.0],
})
print(df)

     a    b    c
0  1.0  2.0  3.0
1  NaN  NaN  NaN
2  NaN  3.0  4.0
3  4.0  NaN  5.0

In [39]:

# 1. how="any" (디폴트) → 하나라도 결측치면 제거
df.dropna(how="any")

     a    b    c
0  1.0  2.0  3.0

In [40]:

# 2. how="all" → 모두 결측치일 때만 제거
df.dropna(how="all")

     a    b    c
0  1.0  2.0  3.0
2  NaN  3.0  4.0
3  4.0  NaN  5.0

In [41]:
# 3. thresh=2 → 결측치가 아닌 값이 2개 이상인 행만 유지
df.dropna(thresh=2)

     a    b    c
0  1.0  2.0  3.0
2  NaN  3.0  4.0
3  4.0  NaN  5.0

In [42]:
# 4. subset → 특정 컬럼만 기준으로 삼기
# a 컬럼 기준, a가 NaN인 행만 제거
df.dropna(subset=["a"])

     a    b    c
0  1.0  2.0  3.0
3  4.0  NaN  5.0

In [ ]:
df

In [ ]:
# 5. axis=1 → 행이 아닌 열 기준으로 제거
df.dropna(axis=1, how="any")