In [ ]:
# pandas에는 merge()도 있고 join()도 있음
# join()은  인덱스 기준이 디폴트
# merge()는 컬럼 기준이 디폴트

# 사용 형태는 pd.merge(df1, df2)의 함수형과 df1.join(df2)의 객체지향 방식

In [ ]:
# merge

In [1]:
import pandas as pd 
import numpy as np

In [2]:
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})

df1

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

In [3]:
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
                    'hire_date': [2004, 2008, 2012, 2014]})

df2

  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014

In [ ]:
# one-to-one join

# 'employee' 컬럼을 키로, 양쪽 데이터프레임에서 값이 일치하는 행끼리 가로로 이어 붙임
# "양쪽 데이터프레임에서 값이 일치하는" → inner join에 해당 이너조인은 공통된 값을 기준으로 두개의 테이블에 같은 값을 기준으로 출력됨
df3 = pd.merge(df1, df2)

# on 파라미터를 사용해서 어떤 컬럼을 기준으로 할 지 지정
# on 파라미터를 사용하지 않으면 이름이 같은 컬럼을 기준으로 사용
# pd.merge(df1, df2, on='employee')

df3

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [5]:

# df1: employee와 location 컬럼이 있음
df_1 = pd.DataFrame({
    'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
    'location': ['Seoul', 'Busan', 'Seoul', 'Daegu'],
    'group': ['Accounting', 'Engineering', 'Engineering', 'HR']
})

# df2: df1과 마찬가지로 employee, location 컬럼이 있음
df_2 = pd.DataFrame({
    'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
    'location': ['Seoul', 'Busan', 'Incheon', 'Daegu'],
    'hire_date': [2008, 2012, 2004, 2014]
})

# Lisa의 df1의 location과 df2의 location이 다름
# employee, location 값이 df1, df2 모두 동일하게 있어야 결과에 포함

In [6]:
df_1

  employee location        group
0      Bob    Seoul   Accounting
1     Jake    Busan  Engineering
2     Lisa    Seoul  Engineering
3      Sue    Daegu           HR

In [7]:
df_2

  employee location  hire_date
0      Bob    Seoul       2008
1     Jake    Busan       2012
2     Lisa  Incheon       2004
3      Sue    Daegu       2014

In [8]:
df_3 = pd.merge(df_1, df_2)
df_3

  employee location        group  hire_date
0      Bob    Seoul   Accounting       2008
1     Jake    Busan  Engineering       2012
2      Sue    Daegu           HR       2014

In [ ]:
# many-to-one join
#many-to-one 1:1 m:m m:1

df3

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [10]:
df4 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'HR'],
                    'supervisor': ['Carly', 'Guido', 'Steve']})
df4

         group supervisor
0   Accounting      Carly
1  Engineering      Guido
2           HR      Steve

In [ ]:
# df3와 df4에서 겹치는 컬럼은 group
# df3에서 group 컬럼의 값은 "many" many는 key 역할을 하지 못함
# df4에서 group 컬럼의 값은 "one" 원은 key역할을 할 수 있고
# 이 경우는 m:1 조인임 
pd.merge(df3, df4)

  employee        group  hire_date supervisor
0      Bob   Accounting       2008      Carly
1     Jake  Engineering       2012      Guido
2     Lisa  Engineering       2004      Guido
3      Sue           HR       2014      Steve

In [12]:
# many-to-many join

df1

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

In [13]:
df5 = pd.DataFrame({'group': ['Accounting', 'Accounting', 'Engineering', 'Engineering', 'HR', 'HR'],
                    'skills': ['math', 'spreadsheets', 'coding', 'linux', 'spreadsheets', 'organization']})
df5

         group        skills
0   Accounting          math
1   Accounting  spreadsheets
2  Engineering        coding
3  Engineering         linux
4           HR  spreadsheets
5           HR  organization

In [14]:
pd.merge(df1, df5)

  employee        group        skills
0      Bob   Accounting          math
1      Bob   Accounting  spreadsheets
2     Jake  Engineering        coding
3     Jake  Engineering         linux
4     Lisa  Engineering        coding
5     Lisa  Engineering         linux
6      Sue           HR  spreadsheets
7      Sue           HR  organization

In [ ]:
#             [df1]                          [df5]
#     employee        group           group          skills
# 0        Bob   Accounting      0   Accounting            math
# 1       Jake  Engineering      1   Accounting    spreadsheets
# 2       Lisa  Engineering      2  Engineering          coding
# 3        Sue           HR      3  Engineering           linux
#                                4           HR    spreadsheets
#                                5           HR    organization

In [15]:
# 데이터프레임 별로 컬럼 이름이 다른 경우; 'left_on', 'right_on'
# 'left_on', 'right_on'는 조인(Join)의 종류와 별개의 옵션

df1

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

In [16]:
df6 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'salary': [70000, 80000, 120000, 90000]})
df6

   name  salary
0   Bob   70000
1  Jake   80000
2  Lisa  120000
3   Sue   90000

In [ ]:
# df1과 df6의 employee 컬럼과 name 컬럼
# 두개의 칼럼의 이름은 다르지만 내부의 값은 같기때문에 저런식으로 직접 이어줘야함,
pd.merge(df1, df6, left_on='employee', right_on='name')

  employee        group  name  salary
0      Bob   Accounting   Bob   70000
1     Jake  Engineering  Jake   80000
2     Lisa  Engineering  Lisa  120000
3      Sue           HR   Sue   90000

In [18]:
# 'left_on', 'right_on' + 여러 개의 컬럼

# df_left: 컬럼명이 'id', 'name'
df_left = pd.DataFrame({
    'id': [1, 2, 3],
    'name': ['Bob', 'Jake', 'Lisa'],
    'group': ['Accounting', 'Engineering', 'Engineering']
})

# df_right: 컬럼명이 'emp_id', 'emp_name'
df_right = pd.DataFrame({
    'emp_id': [1, 2, 3],
    'emp_name': ['Bob', 'Jake', 'Lisa'],
    'hire_date': [2008, 2012, 2004]
})

In [19]:
df_left

   id  name        group
0   1   Bob   Accounting
1   2  Jake  Engineering
2   3  Lisa  Engineering

In [20]:
df_right

   emp_id emp_name  hire_date
0       1      Bob       2008
1       2     Jake       2012
2       3     Lisa       2004

In [ ]:
# left_on과 right_on에 여러개의 칼럼을 넣음 (리스트를 넘김)
df_merged = pd.merge(df_left, df_right, 
                     left_on=['id', 'name'], 
                     right_on=['emp_id', 'emp_name'])

df_merged

   id  name        group  emp_id emp_name  hire_date
0   1   Bob   Accounting       1      Bob       2008
1   2  Jake  Engineering       2     Jake       2012
2   3  Lisa  Engineering       3     Lisa       2004

In [ ]:
# 1:M, M:M는 데이터에 따라 Pandas가 알아서 처리

In [22]:
df1

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

In [ ]:
df1_employee = df1.set_index('employee') #employee칼럼을 인덱스로 세팅함
df1_employee

                group
employee
Bob        Accounting
Jake      Engineering
Lisa      Engineering
Sue                HR

In [26]:
df2

  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014

In [ ]:
df2_employee = df2.set_index('employee') # employee칼럼을 인덱스로 세팅함
df2_employee

          hire_date
employee
Lisa           2004
Bob            2008
Jake           2012
Sue            2014

In [ ]:
pd.merge(df1_employee, df2_employee, left_index=True, right_index=True)
#merge는 칼럼 기준인데 인덱스를 기준으로 하기 위해서 저런 코드를 추가함
# 양쪽 데이터프레임의 인덱스 번호(또는 이름)가 같은 것끼리 join
#사실 서로의 기본값이 머지는 칼럼이고 조인은 인덱스일뿐이지 서로 반데로 인덱스와 칼럼으로도 조인할수있음

                group  hire_date
employee
Bob        Accounting       2008
Jake      Engineering       2012
Lisa      Engineering       2004
Sue                HR       2014

In [28]:
# 한쪽은 인덱스, 한쪽은 컬럼을 기준으로 join

df1_index = pd.DataFrame({
    'group': ['Accounting', 'Engineering', 'Engineering', 'HR']
}, index=['Bob', 'Jake', 'Lisa', 'Sue'])
df1_index

            group
Bob    Accounting
Jake  Engineering
Lisa  Engineering
Sue            HR

In [29]:

# name 컬럼
df2_column = pd.DataFrame({
    'name': ['Lisa', 'Bob', 'Jake', 'Sue'],
    'hire_date': [2004, 2008, 2012, 2014]
})
df2_column

   name  hire_date
0  Lisa       2004
1   Bob       2008
2  Jake       2012
3   Sue       2014

In [30]:
# 왼쪽은 인덱스, 오른쪽은 'name' 컬럼
df_merged = pd.merge(df1_index, df2_column, left_index=True, right_on='name')

df_merged

# name을 인덱스로 하려면
# df_merged.set_index('name')

         group  name  hire_date
1   Accounting   Bob       2008
2  Engineering  Jake       2012
0  Engineering  Lisa       2004
3           HR   Sue       2014

위의 두 부분은 다시봐야함

In [31]:
df7 = pd.DataFrame({'name': ['Peter', 'Paul', 'Mary'],
                    'food': ['fish', 'beans', 'bread']},
                   columns=['name', 'food'])
df7

    name   food
0  Peter   fish
1   Paul  beans
2   Mary  bread

In [32]:

df8 = pd.DataFrame({'name': ['Mary', 'Joseph'],
                    'drink': ['wine', 'beer']},
                   columns=['name', 'drink'])
df8

     name drink
0    Mary  wine
1  Joseph  beer

In [33]:
# 1:M, M:M는 데이터에 따라 Pandas가 알아서 처리
# join 방식(how='inner', 'outer', 'left', 'right')은 how 파라미터로 지정
# 둘은 별개


# how를 지정하지 않으면 디폴트는 inner
# inner: 양쪽 모두에 있는 값만 결과에 포함
pd.merge(df7, df8)

   name   food drink
0  Mary  bread  wine

In [ ]:
# inner는 교집합
# outer는 합집합
# outer: 양쪽 한 군데라도 있으면 결과에 포함
# => 안에 있는걸 다 가져온다는거임
pd.merge(df7, df8, how='outer')

# 근데 이러면 결측치가 생기는데 이유는 그냥 다 가져오기때문에 다른 테이블에 값이 없다면 그 값은 입력되지 않았기 떄문에 결측치가 생김
#판다의 결측치는 NaN = 실수인 경우, NA => 실수형

     name   food drink
0  Joseph    NaN  beer
1    Mary  bread  wine
2    Paul  beans   NaN
3   Peter   fish   NaN

In [35]:
df7.dtypes

name    str
food    str
dtype: object

In [36]:
df8.dtypes

name     str
drink    str
dtype: object

In [37]:
# dtype="string"를 사용해야 결측치가 NA가 됨

df7 = pd.DataFrame({'name': ['Peter', 'Paul', 'Mary'],
                    'food': ['fish', 'beans', 'bread']},
                   dtype="string")

df8 = pd.DataFrame({'name': ['Mary', 'Joseph'],
                    'drink': ['wine', 'beer']},
                   dtype="string")

pd.merge(df7, df8, how='outer')

     name   food drink
0  Joseph   <NA>  beer
1    Mary  bread  wine
2    Paul  beans  <NA>
3   Peter   fish  <NA>

In [ ]:
# 너는 고향이 어디니? 저는 _x(왼쪽), _y(오른쪽) 입니다~

df9 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'], 'rank': [1, 2, 3, 4]})
df10 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'], 'rank': [3, 1, 4, 2]})
# 9와10은 서로 다른 자료를 집계한거일수도 있기떄문에 칼럼명만 같다고 조인을 저렇게 하면 안됨

In [39]:
df9

   name  rank
0   Bob     1
1  Jake     2
2  Lisa     3
3   Sue     4

In [40]:
df10

   name  rank
0   Bob     3
1  Jake     1
2  Lisa     4
3   Sue     2

In [ ]:
pd.merge(df9, df10, on= 'name') #name만을 사용해서 오른쪽과 왼쪽을 x랑 y로 저리함 엑스 와이는 자동 우리가 따로 지정하지 않음
#prefix, 얘가 앞에 붙는거 suffix 얘가 뒤에 붙는거 접미사, 접두사

   name  rank_x  rank_y
0   Bob       1       3
1  Jake       2       1
2  Lisa       3       4
3   Sue       4       2

In [ ]:
# _x, _y말고 다른 걸로...

pd.merge(df9, df10, on='name', suffixes=['_L', '_R']) #기본인 x,y가 맘에 들지 않으면 직접 우리가 값을 전달하면 됨

   name  rank_L  rank_R
0   Bob       1       3
1  Jake       2       1
2  Lisa       3       4
3   Sue       4       2